* Mescal
Mescal is an in memory key/value store written in Go.

** Setup for development

- Install Go (http://golang.org)
- Install capnproto (https://capnproto.org/install.html)
- Install Mescal dependencies

#+BEGIN_SRC bash
$ go get -u -t zombiezen.com/go/capnproto/...
$ go get github.com/onsi/ginkgo/ginkgo
$ go get github.com/onsi/gomega
#+END_SRC

** Run tests
#+BEGIN_SRC bash
$ ginkgo -r
#+END_SRC

** Build server
#+BEGIN_SRC bash
$ cd server
$ go build -i
#+END_SRC

** Build client
#+BEGIN_SRC bash
$ cd client
$ go build -i
#+END_SRC

** License
The MIT License (MIT)

Copyright (c) 2015 Brady Love <love.brady@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
