* Mescal
Mescal is an in memory key/value store written in Go.

** Setup for development

- Install Go (http://golang.org)
- Install Mescal dependencies (`./get-deps.sh`)

** Features
- [X] gRPC Transport
- [X] Support value types
  - [X] String
  - [X] Int64
  - [X] Float64
- [ ] Commands
  - [ ] Set
  - [ ] Get
  - [ ] Increment
  - [ ] Decrement
  - [ ] Delete
  - [ ] Stat
  - [ ] Ping
- [ ] Watch for changes to a keys value
- [ ] TLS
- [ ] MutualTLS
- [ ] Expiration/Cleanup of expired keys/values
- [ ] REPL client
- [ ] Go client library
- [ ] Ruby client library
- [ ] Graceful server shutdown
- [ ] Distributed servers

** License
The MIT License (MIT)

Copyright (c) 2017 Brady Love <love.brady@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
